theme: jekyll-theme-minimal

plugins:
  - jekyll-relative-links
  - jekyll-sitemap
  
relative_links:
  enabled: true
  collections: true

#title: Luis A. Echeverria's Personal Website
description: Luis A. Echeverria's Personal Website

# include:
#   - index.md

# collections:
#   - skills
